nx611j: delineage it and avoid compilation error device/nubia/nx611j/doze/src/org/lineageos/settings/doze/DozeSettingsFragment.java:111: error: cannot find symbol                 R.string.switch_bar_on : R.string.switch_bar_off));                         ^   symbol:   variable switch_bar_on   location: class string device/nubia/nx611j/doze/src/org/lineageos/settings/doze/DozeSettingsFragment.java:111: error: cannot find symbol                 R.string.switch_bar_on : R.string.switch_bar_off));                                                  ^   symbol:   variable switch_bar_off   location: class string device/nubia/nx611j/doze/src/org/lineageos/settings/doze/DozeSettingsFragment.java:136: error: cannot find symbol         mTextView.setText(getString(isChecked ? R.string.switch_bar_on : R.string.switch_bar_off));                                                         ^   symbol:   variable switch_bar_on   location: class string device/nubia/nx611j/doze/src/org/lineageos/settings/doze/DozeSettingsFragment.java:136: error: cannot find symbol         mTextView.setText(getString(isChecked ? R.string.switch_bar_on : R.string.switch_bar_off));                                                                                  ^   symbol:   variable switch_bar_off   location: class string 4 errors
(cherry picked from commit cca3609cf79ac7d212ce7e4f89d342a8dde51fad)